export const GET_DOCTORS_REQUEST = "GET_DOCTORS_REQUEST";
export const GET_DOCTORS_REQUEST_SUCCESS = "GET_DOCTORS_REQUEST_SUCCESS";
export const GET_DOCTORS_REQUEST_FAIL = "GET_DOCTORS_REQUEST_FAIL";

export const GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST";
export const GET_SERVICES_REQUEST_SUCCESS = "GET_SERVICES_REQUEST_SUCCESS";
export const GET_SERVICES_REQUEST_FAIL = "GET_SERVICES_REQUEST_FAIL";

// export const GET_ALL_REQUEST = "GET_ALL_REQUEST";
// export const GET_ALL_REQUEST_SUCCESS = "GET_ALL_REQUEST_SUCCESS";
// export const GET_ALL_REQUEST_FAIL = "GET_ALL_REQUEST_FAIL";

export const CHANGE_APPOINTMENT_SHEDULE= "CHANGE_APPOINTMENT_SHEDULE";
export const CHANGE_APPOINTMENT_DOCTOR= "CHANGE_APPOINTMENT_DOCTOR";
export const CHANGE_APPOINTMENT_TIME= "CHANGE_APPOINTMENT_TIME";
export const CHANGE_APPOINTMENT_SPEC= "CHANGE_APPOINTMENT_SPEC";
export const CHANGE_APPOINTMENT_COMMENT= "CHANGE_APPOINTMENT_COMMENT";
export const CLEAR_APPOINTMENT= "CLEAR_APPOINTMENT";

export const AUTH_REQUEST = "GET_AUTH_REQUEST";
export const AUTH_REQUEST_SUCCESS = "AUTH_REQUEST_SUCCESS";
export const AUTH_REQUEST_FAIL = "AUTH_REQUEST_FAIL";

export const REGISTRATION_REQUEST = "REQISTRATION_REQUEST";
export const REGISTRATION_REQUEST_SUCCESS = "REGISTRATION_REQUEST_SUCCESS";
export const REGISTRATION_REQUEST_FAIL = "REGISTRATION_REQUEST_FAIL";

export const POST_DOCTORS_REQUEST = "POST_DOCTORS_REQUEST";
export const POST_DOCTORS_REQUEST_SUCCESS = "POST_DOCTORS_REQUEST_SUCCESS";
export const POST_DOCTORS_REQUEST_FAIL = "POST_DOCTORS_REQUEST_FAIL";

export const POST_SERVICES_REQUEST = "POST_SERVICES_REQUEST";
export const POST_SERVICES_REQUEST_SUCCESS = "POST_SERVICES_REQUEST_SUCCESS";
export const POST_SERVICES_REQUEST_FAIL = "POST_SERVICES_REQUEST_FAIL";

export const POST_ORDERS_REQUEST = "POST_ORDERS_REQUEST";
export const POST_ORDERS_REQUEST_SUCCESS = "POST_ORDERS_REQUEST_SUCCESS";
export const POST_ORDERS_REQUEST_FAIL = "POST_ORDERS_REQUEST_FAIL";

export const POST_SHEDULE_REQUEST = "POST_SHEDULE_REQUEST";
export const POST_SHEDULE_REQUEST_SUCCESS = "POST_SHEDULE_REQUEST_SUCCESS";
export const POST_SHEDULE_REQUEST_FAIL = "POST_SHEDULE_REQUEST_FAIL";

export const PUT_DOCTORS_REQUEST = "PUT_DOCTORS_REQUEST";
export const PUT_DOCTORS_REQUEST_SUCCESS = "PUT_DOCTORS_REQUEST_SUCCESS";
export const PUT_DOCTORS_REQUEST_FAIL = "PUT_DOCTORS_REQUEST_FAIL";

// export const CHANGE_SHEDULE_DATE= "CHANGE_SHEDULE_DATE";
export const CHANGE_SHEDULE_DOCTOR= "CHANGE_SHEDULE_DOCTOR";

export const CHANGE_INPUT_VALUE_DOCTOR_FORM= "CHANGE_INPUT_VALUE_DOCTOR_FORM";

export const CHANGE_SELECTED_DOCTOR= "CHANGE_SELECTED_DOCTOR";



